### PR TITLE
due to removal of API getUsagesString from nsIX509Cert this plugin was not working anymore

### PR DESCRIPTION
**Pull request by sharapanoff**
removed the call to the API as it was sujested by David Keeler
https://bugzilla.mozilla.org/show_bug.cgi?id=1309690#c9

### CODE REVIEW

**Comment by jasp00** [comment]
@sharapanoff, sorry about the lack of answer, I do not have the time yet.

The proper fix is to use replacements from the NSS library, if possible. Your proposal would work as a workaround, but could you wrap it up with `try` and `catch` instead?

**Comment by sharapanoff** [comment]
i've put the call to getUsagesString in TRY/CATCH

**Comment by dab18** [comment]
when can expect the release on https://addons.mozilla.org/ru/firefox/addon/signtextjs-plus/ ?

**Comment by jasp00** [comment]
Thanks for the patch. I see that Firefox 50 has been released. I will try to update the add-on around Saturday. Sorry for the delay.

**Pull request merged**
